# This file started out as a copy of the default nav2_params.yaml, but has been heavily modified for the Amiga robot.
#
# this was the command: cp /opt/ros/humble/share/nav2_bringup/params/nav2_params.yaml custom_navigation/config/nav2_params.yaml
#
# Changes too numerous to list here. 
# A lot of parameters have been changed in a attempt to have the project build, the project then did not build, but we kept the changes anyway.
# Due to time presure we could not optimise the parameters, a lot of them are likely wrong.

# Known capabilities of this Nav2 stack:
# -  It can drive in a 100x100m field.
# -  It is higly succesful at completing a waypoint first try. (if the waypoint is placed correctly, see known issues)
# -  It can turn on the spot.
# -  It can turn while driving.
# -  Automatic recovery behavior exist. But is unlikely to help when stuck.

# Known issues of the this nav2 stack:
# -  Placing a waypoint behind the robot will garentee recovery behavior to be triggered. And the goal will most likely fail.
#    When a waypoint is placed more then 90 degrees from the current heading it will fail to reach the waypoint. This is likely because of the controller server.
#    As of now the controller server is of type DWB controller, The default controller from the turtlebot, which is known to have this issue. (see our suggested actions below)
# -  Persision is terrible, we had to keep tolerances very high to get the robot to reach waypoints.

# Suggested actions:
# -  Change the controller server to a different controller. The RegulatedPurePersuit controller should work: 
#    https://github.com/ros-navigation/navigation2/tree/main/nav2_regulated_pure_pursuit_controller
#    However, our original plan was to make a hyper presice navigation stack for archicultural use. for that this controller would work even better:
#    https://github.com/decwest/nav2_dynamic_window_pure_pursuit_controller/tree/humble
#    See if you can make the DWPP controller work.
# -  change backup behavior to be a simple stop, or drive back and restart navigating. The goal was to have the robot never drive over plants while tilling.
#    However, we did not have the time to change the default turtlebot behavior.
# -  There might be some nodes or parameters that are not needed. Their purpourse was to serve a turtlebot with slam, not a GPS-RTK Amiga robot. but we did not have the time to clean up the code.
#    We suggest you research the nav2 stack and remove any unneeded nodes or parameters. This will make it easier to understand and modify the code.

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: odom
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_remove_passed_goals_action_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 15.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      # these should be reverted to presice values post controller fix
      xy_goal_tolerance: 0.50 # larger goal tolerance otherwise the bot wil furiously spin in circles trying to reach the exact waypoint
      yaw_goal_tolerance: 3.14159 # 360 degrees, the bot does not care about heading

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True

      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.60 # speed. can also be set on the amiga terminal.
      max_vel_y: 0.0               
      max_vel_theta: 0.50 # rotation speed. keep it high otherwise the bot will engage motors but strong grip and friction will prevent it from turning
      min_speed_xy: 0.0
      max_speed_xy: 0.60
      min_speed_theta: 0.20 # minimum rotation speed. keep it high otherwise the bot will engage motors but strong grip and friction will prevent it from turning

      # acceleration limits have been increased. needed to make the bot overcome the strong grip and friction of the wheels. otherwise it will not move
      acc_lim_x: 0.80
      acc_lim_y: 0.0
      acc_lim_theta: 1.20
      decel_lim_x: -0.80
      decel_lim_y: 0.0
      decel_lim_theta: -1.20

      vx_samples: 20
      vy_samples: 1             
      vtheta_samples: 30         
      sim_time: 1.5               

      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.5    
      xy_goal_tolerance: 0.50   
      trans_stopped_velocity: 0.20
      short_circuit_trajectory_evaluation: True
      stateful: True

      # removed turning in place bacause it just made the bot occilate in its place. can possibly fix the 180 degree turn issue by enabling it again, but we did not have time to fix it.
      # replacing the controller with a better controller (RPP or DWPP) is still adviced, rather then waisting effort on fixing the DWB controller
      critics: ["Oscillation", "BaseObstacle", "PathAlign", "PathDist", "GoalDist", "GoalAlign"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.30
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      GoalAlign.scale: 4.0                  
      GoalAlign.forward_point_distance: 0.30

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 6                     
      height: 6
      resolution: 0.05
      robot_radius: 1.10 # 1.1m because the bot is about 2m wide
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5
        inflation_radius: 1.40 # even bigger than robot radius, to make turns as succesfull as possible.
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 100
      height: 100
      use_sim_time: False
      robot_radius: 1.10
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5
        inflation_radius: 1.40
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "empty_map"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.50 # matches max_vel_theta
    min_rotational_vel: 0.25 # higher than min_speed_theta to overcome grip of the wheels even better.
    rotational_acc_lim: 1.20 # matches acc_lim_theta

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.60, 0.0, 0.50] # matches controller velocity limits
    min_velocity: [-0.60, 0.0, -0.50]
    max_accel: [0.80, 0.0, 1.20] # matches controller acceleration limits
    max_decel: [-0.80, 0.0, -1.20]
    odom_topic: "/odometry/filtered"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0